2nb_letters: 20
nb_possible_chars: 27
possible_letters: ' abcdefghijklmnopqrstuvwxyz'
WEIGHTS_URL: 'https://raw.githubusercontent.com/eemkos/ModelWeights/master/weights.hdf5'
MODEL_URL: 'https://raw.githubusercontent.com/eemkos/ModelWeights/master/model.json'

MODELS_URLS: ['https://raw.githubusercontent.com/eemkos/ModelWeights/master/model.json', 
              'https://raw.githubusercontent.com/eemkos/ModelWeights/master/model.json',
              'https://raw.githubusercontent.com/eemkos/ModelWeights/master/model.json']
              
WEIGHTS_URLS: ['https://raw.githubusercontent.com/eemkos/ModelWeights/master/weights.hdf5',
                'https://raw.githubusercontent.com/eemkos/ModelWeights/master/weights.hdf5',
                'https://raw.githubusercontent.com/eemkos/ModelWeights/master/weights.hdf5']
                
MODELS_INFOS: [{nb_letters: 20, nb_possible_chars: 27},
                {nb_letters: 20, nb_possible_chars: 27},
                {nb_letters: 20, nb_possible_chars: 27}]
